services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - VITE_API_URL=${API_URL:-http://localhost:8080}
        ports:
            # We map to 80 because Nginx runs on 80
            # You can change the host port (left side) if 80 is busy
            - "80:80"
        restart: always